# -*- mode: ruby -*-
# vi: set ft=ruby :

#https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration
Vagrant.configure("2") do |config|

  # VagrantBox que se usara para levantar.
  config.vm.box = "ubuntu/jammy64"
  
  #Nombre de la pc dentro del Sistema Operativo
  config.vm.hostname = "VMPruebas"
  
  config.vm.synced_folder '.', '/home/vagrant/carpeta_compartida'
  
  #Configuracion de Red
  config.vm.network "private_network", :name => '', ip: "192.168.56.2"
  
  #Configuraciones de la VM en VirtualBox
  config.vm.provider "virtualbox" do |vb|
    #Cantidad de RAM
    vb.memory = "2048"
    #Cantidad de Procesadores
    vb.cpus = 2

    #Nombre de la VM en VirtualBox 
    vb.name = "VMPruebas"
    
    # Habilitar clones enlazados en VirtualBox
    vb.linked_clone = true

    # Mostrar interfaz gráfica de la VM en VirtualBox
    vb.gui = false
    
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sudo systemctl restart sshd
  SHELL
  config.ssh.insert_key = false

  # Mensaje post-up...
  config.vm.post_up_message = "  vagrant ssh          # Ingresa por linea de comandos a la vm"


end
